# Generated by Django 5.1.1 on 2024-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_entry_jogo_delete_memoria_entry_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='tempo',
            field=models.CharField(max_length=10),
        ),
    ]
